### ISSUE TITLE
Error when installing puppet module 

### ISSUE THREAD

**Issue by mamann** [crayfishx/puppet-db2#18]
Hi guys,

I was more than amazed to see, that there is a DB2 puppet module. Unfortunately I cannot use the module with the latest puppet verison (4.8.1). 

Whenever I try to install the module calling

`puppet module install crayfishx-db2 --version 1.2.0`

puppet reports the following error:

> Error: Could not install module 'crayfishx-db2' (???)
>   No version of 'crayfishx-db2' can satisfy all dependencies
>     Use `puppet module install --ignore-dependencies` to install only this module

Do you have an idea how I could fix this?

Regards
Michael

**Comment by crayfishx** [comment]
Hi @mamann thanks for reporting this... I can't reproduce this, it installs fine for me - maybe Puppet is being a bit vague in how it's reporting the error.  I'm thinking maybe that you have one of the dependencies installed (archive, stdlib...etc) that is higher than one of the dependency limits of the db2 module.   Can you paste the contents of `puppet module list --tree` for me?

Also - what OS are you installing this to?

Thanks

**Comment by mamann** [comment]
Hi @crayfishx thanks for your fast reply ... I really appreciate it. When running the command, I received the following warning:

> Warning: Module 'puppet-archive' (v1.2.0) fails to meet some dependencies:
>  'crayfishx-db2' (v1.2.0) requires 'puppet-archive' (>= 0.5.0 < 1.0.0)

So your assumption was correct.

This is the full output:

> ├── tylerwalts-jdk_oracle (v1.5.0)
> ├─┬ puppetlabs-postgresql (v4.8.0)
> │ ├── puppetlabs-stdlib (v4.14.0)
> │ ├── puppetlabs-apt (v2.3.0)
> │ └── puppetlabs-concat (v1.2.5)
> ├── puppetlabs-ntp (v6.0.0)
> ├─┬ puppet-jira (v3.0.1)
> │ ├── puppet-archive (v1.2.0)
> │ └── puppet-staging (v2.1.0)
> ├── crayfishx-db2 (v1.2.0)
> └─┬ icinga-icingaweb2 (v1.0.6)
>   ├── puppetlabs-apache (v1.11.0)
>   ├── puppetlabs-inifile (v1.6.0)
>   └── puppetlabs-vcsrepo (v1.5.0)

Could you please take a look at this? I would really like to use the DB2 module to setup the DB2 instances on my servers.

Thanks in advance

**Comment by crayfishx** [comment]
@mamann yes, looks like you are running puppet-archive 1.2.0 and the module requres < 1.0.0 - I think we can safely up the requirement here to < 2.0.0 - I'll have a look at that shortly and release a new version

**Comment by crayfishx** [comment]
@mamann The fix for this was released to the forge as 1.2.1 - please let me know if this works.
