### ISSUE TITLE
db2:instance Not Supporting Port Number Assignment

### ISSUE THREAD

**Issue by bellds** [crayfishx/puppet-db2#4]
It would be nice if the db2::instance supported setting the instance's port or service name.

**Comment by crayfishx** [comment]
@bellds happy to add this enhancement - do you have some examples of how to set these?

**Comment by bellds** [comment]
The DB2 Knowledge Center says the -p option on Linux with the port number or name (in /etc/services) and on Windows a range is entered with the -r option.

http://www.ibm.com/support/knowledgecenter/SSEPGG_9.7.0/com.ibm.db2.luw.admin.cmd.doc/doc/r0002057.html

I am in meetings all this week, I will try to post an actual command in the coming days.

**Comment by crayfishx** [comment]
This was released as part of 1.0.0..... thx
